baseURL = "https://flynncao.uk"
languageCode = "zh-Hans"
defaultContentLanguage = "zh"
title = "Majimay的四次元口袋"
theme = "dream"
enableGitInfo = true
enableRobotsTXT = true

hasCJKLanguage = true


[markup]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
noClasses = false

[params]
lightTheme = "emerald"
darkTheme = "dark"


#backgroundImage = "/me/00480681_p0.jpg"
#backgroundImageDark = "me/nrze427er2zb1.jpg"

images = ["me/background.jpg"]

author = "flynncao"
description = "The life record of Flynn Cao is presented here."
avatar = "/me/avatar2.jpeg"
headerTitle = "Majimay的四次元口袋"
motto = "Sometimes you never realize the value of a moment until it becomes a memory."

footerBottomText = ""

rss = true

utterancesRepo = "flynncao/flynncao.github.io"

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""
# VALINE_LANGUAGE = ""
waline = true
# walineServer = "https://waline.flynncao.uk"
walineServer = "https://walineserermajimayblog.vercel.app/"


email = "realflynncao@gmail.com"

siteStartYear = 2022

favicon = "/favicon.ico"

# Syntax highlighting
customSyntaxHighlighting = true

# options
showSummaryCoverInPost = true
hasTwitterEmbed = true
stickyNav = true
reorderNavItems = ["search", "github", "posts", "categories", "tags", "rss"]
collapseNavItems = ["posts", "categories", "tags", "rss"]
# noDefaultSummaryCover = true
showTableOfContents = true
showPrevNextPost = true


[params.advanced]
customCSS = ["css/custom.css"]
# customJS = []

[params.experimental]
jsDate = true
jsDateFormat = "yyyy年MM月dd日"
# jsDateFormat = "yyyy年MM月dd日，cccc"

[services]
[services.googleAnalytics]
ID = 'G-6XW7QWCBGK'

[languages]
  [languages.zh]
	languageCode=  'zh-Hans'
	languageName = 'Chinese'
    languageDirection = 'ltr'
    title = 'Majimay的四次元口袋'
    weight = 1
  [languages.en]
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Majimay Blog'
    weight = 2
    [languages.en.params]
      subtitle = 'Reference, Tutorials, and Explanations'	
